/* **********************************************************************************************
  WARNING: DO NOT EDIT this file except from inside the react-starter-template repository. Changes made to this file inside child repos will NOT be reflected in the parent source template repository, and will generate code conflicts.
*********************************************************************************************** */
import React from 'react';
import PropTypes from 'prop-types';

// https://medium.com/@david.gilbertson/icons-as-react-components-de3e33cb8792

const Icon = ({
  verticalAlign,
  color,
  size,
  viewBox,
  path,
}) => {
  const styles = {
    svg: {
      display: 'inline-block',
      verticalAlign,
    },
    path: {
      fill: color,
    },
  };

  return (
    <svg
      style={styles.svg}
      width={`${size}px`}
      height={`${size}px`}
      viewBox={viewBox}
      preserveAspectRatio="xMidYMid meet"
    >
      <g>
        {path.split(',').map((p, index) => (
          <path
            key={['path', index].join('_')}
            style={styles.path}
            d={p}
          >
          </path>
        ))}
      </g>
    </svg>
  );
};

Icon.propTypes = {
  path: PropTypes.string.isRequired,
  size: PropTypes.number,
  color: PropTypes.string,
  viewBox: PropTypes.string,
  verticalAlign: PropTypes.string,
};

Icon.defaultProps = {
  size: 16,
  verticalAlign: 'middle',
  color: 'currentColor',
  viewBox: '0 0 16 16',
};

export default Icon;
