/* **********************************************************************************************
  WARNING: DO NOT EDIT this file except from inside the react-starter-template repository. Changes made to this file inside child repos will NOT be reflected in the parent source template repository, and will generate code conflicts.
*********************************************************************************************** */
import React from 'react';
import PropTypes from 'prop-types';
import 'template/styles/components/LoadingAnimation.css';

const LoadingAnimation = ({
  size,
  marginTop,
  message,
}) => {
  switch (size) {
    case 'small':
      return (
        <div style={{ marginTop, textAlign: 'center' }}>
          <div style={{ marginTop: '30px' }} className="cssload-loader-small">
            <div className="cssload-dot-small"></div>
            <div className="cssload-dot-small"></div>
            <div className="cssload-dot-small"></div>
            <div className="cssload-dot-small"></div>
            <div className="cssload-dot-small"></div>
          </div>
          <div style={{ paddingTop: '250px' }}>{message}</div>
        </div>
      );
    default:
      return (
        <div style={{ marginTop, textAlign: 'center' }}>
          <div style={{ marginTop: '30px' }} className="cssload-loader">
            <div className="cssload-dot"></div>
            <div className="cssload-dot"></div>
            <div className="cssload-dot"></div>
            <div className="cssload-dot"></div>
            <div className="cssload-dot"></div>
          </div>
          <div style={{ paddingTop: '250px' }}>{message}</div>
        </div>
      );
  }
};

LoadingAnimation.propTypes = {
  size: PropTypes.string,
  message: PropTypes.string,
  marginTop: PropTypes.string,
};

LoadingAnimation.defaultProps = {
  name: 'large',
  message: 'Loading...',
  marginTop: '15px',
};

export default LoadingAnimation;
