/* **********************************************************************************************
  WARNING: DO NOT EDIT this file except from inside the react-starter-template repository. Changes made to this file inside child repos will NOT be reflected in the parent source template repository, and will generate code conflicts.
*********************************************************************************************** */
import React from 'react';
import gql from 'graphql-tag';
import queryString from 'query-string';
import { Mutation, graphql } from 'react-apollo';
import { withRouter } from 'react-router-dom';
import { Redirect } from 'react-router';
import RegisterCode from 'template/RegisterCode';
import { GET_USER_INFO } from 'template/Queries';
import Error from 'template/shared/Error';
import LoadingAnimation from 'template/shared/LoadingAnimation';

const REGISTER_CODE = gql`
  mutation registerCode($code: String!, $redirect_uri: String!) {
    registerCode(code: $code, redirect_uri: $redirect_uri) {
      loggedIn
      message
      reason
    }
  }
`;

class Login extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isLoggedIn: false,
      message: 'No message',
      fail: false,
    };
  }

  render() {
    const {
      location: {
        search,
      },
      history,
    } = this.props;
    const { code } = queryString.parse(search);
    return (
      <Mutation
        mutation={REGISTER_CODE}
        refetchQueries={() => ([{
          query: GET_USER_INFO,
        }])}
        awaitRefetchQueries
        onCompleted={(data) => {
          this.setState({
            isLoggedIn: data.registerCode.loggedIn,
            message: data.registerCode.message,
            fail: !data.registerCode.loggedIn,
          }, () => {
            const { isLoggedIn } = this.state;
            if (isLoggedIn) {
              localStorage.setItem('loggedIn', true);
              const priorPath = localStorage.getItem('preLoginPathname');
              if (priorPath) {
                if (priorPath !== '/login') {
                  const priorSearch = localStorage.getItem('preLoginSearch');
                  if (priorSearch) {
                    history.push(`${priorPath}${priorSearch}`);
                  } else {
                    history.push(priorPath);
                  }
                }
              }
            }
          });
        }}
      >
        {
          (registerCode, { data, error }) => {
            const { isLoggedIn, message } = this.state;
            return (
              <div>
                <RegisterCode
                  registerCode={registerCode}
                  code={code}
                  loggedIn={isLoggedIn}
                >
                  <div>
                    {this.state.fail ? // eslint-disable-line
                      <Error message={message} />
                      : isLoggedIn
                        ? (
                          <Redirect to="/" />
                        )
                        : <LoadingAnimation />
                    }
                  </div>
                </RegisterCode>
              </div>
            );
          }
        }
      </Mutation>
    );
  }
}

export default withRouter(graphql(GET_USER_INFO, { name: 'userInfo' })(Login));
