/* **********************************************************************************************
  WARNING: DO NOT EDIT this file except from inside the react-starter-template repository. Changes made to this file inside child repos will NOT be reflected in the parent source template repository, and will generate code conflicts.
*********************************************************************************************** */
import React from 'react';
import gql from 'graphql-tag';
import { Mutation } from 'react-apollo';
import { withRouter } from 'react-router-dom';
import LogoutCode from 'template/LogoutCode';
import { withUser } from 'template/UserContext';
import Error from 'template/shared/Error';
import LoadingAnimation from 'template/shared/LoadingAnimation';

const LOGOUT_CODE = gql`
  mutation logout {
    logout {
      loggedIn
      message
      reason
    }
  }
`;

class Logout extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isLoggedIn: true, // weird to set this true ...
      message: 'No message',
      fail: false,
    };
  }

  render() {
    return (
      <Mutation
        mutation={LOGOUT_CODE}
        onCompleted={(data) => {
          this.setState({
            isLoggedIn: data.logout.loggedIn,
            message: data.logout.message,
            fail: data.logout.loggedIn,
          }, () => {
            if (!this.state.isLoggedIn) {
              this.props.user.logout();
              localStorage.setItem('loggedIn', false);
              this.props.history.push('/');
            }
          });
        }}
      >
        {
          (logout, { data, error }) => (
            <div>
              <LogoutCode
                logout={logout}
                loggedIn={this.state.isLoggedIn}
              >
                <div>
                  {this.state.fail ? // eslint-disable-line
                    <Error message={this.state.message} />
                    : this.state.loggedIn ?
                      <LoadingAnimation />
                      : <div>You are logged out</div>
                  }
                </div>
              </LogoutCode>
            </div>
          )
        }
      </Mutation>
    );
  }
}

export default withRouter(withUser(Logout));
